### ISSUE TITLE
It's not possible to use this bundle without FosUserBundle

### ISSUE THREAD

**Issue by wdrupal** [ScullWM/MailHookBundle#3]
When i'm trying to install bundle i have an error:

> 
>  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                         
>   The service "swm.mail_hook.hydrator.fos_user" has a dependency on a non-existent service "fos_user.user_manager". 

But i don't see dependency on FosUserBundle in composer.json. Is it possible to use this bundle just for catch webhooks?

**Comment by ScullWM** [comment]
Oh yes! That's a big error i've made. 
I thinks that we can set this service as optionnal for people who don't user FosUserBundle. I will try to fix it soon.

**Comment by ScullWM** [comment]
I've update it, should work now @wdrupal

**Comment by wdrupal** [comment]
Got it, thanks
